spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:wydatex;MODE=MYSQL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/master.xml
  sql:
    init:
      mode: never
  profiles:
    default: dev